<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.rkuo</groupId>
    <artifactId>viddyoop</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <relativePath>../../../pom.xml</relativePath>
  </parent>

  <artifactId>hbx-mapreduce</artifactId>
  <name>HBXMapReduce</name>

  <build>
    <finalName>HBXMapReduce</finalName>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>com.rkuo</groupId>
      <artifactId>rk-utils</artifactId>
    </dependency>
    <dependency>
      <groupId>com.rkuo</groupId>
      <artifactId>rk-ssh-utils</artifactId>
    </dependency>
    <dependency>
      <groupId>com.rkuo</groupId>
      <artifactId>rk-hadoop-utils</artifactId>
    </dependency>
    <dependency>
      <groupId>com.rkuo</groupId>
      <artifactId>hbx-utils</artifactId>
    </dependency>
    <dependency>
      <groupId>com.rkuo</groupId>
      <artifactId>hbx-wrapper-exe</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.dataformat</groupId>
      <artifactId>jackson-dataformat-xml</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-client</artifactId>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</project>
